server:
  port: 8089
  
logging:
  level:
    root: info
    
datasource:
    url: jdbc:mysql://localhost:3306/profile
    username: root
    password: abc12345
    driverClassName: com.mysql.cj.jdbc.Driver
    test-while-idle: true
    validation-query: SELECT 1